name: Trigger Sync and Update

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync and Update in Taktile-Test
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Zachj345/Taktile-Test/dispatches \
          -d '{"event_type": "update_nodes"}'
